### ISSUE TITLE
能不能传个天翼/阿里云盘？

### ISSUE THREAD

**Issue by Heporis** [Freddd13/music-separation-gui#1]
百毒真是折磨😣
以前是被checkpoint下载下到吐了
拒绝百毒，人人有责🤣

**Comment by Heporis** [comment]
把cuda和pytorch单独放出来吧，这两个太大了，cuda需要的可以另外下载，pytorch去官网下都比GitHub快

**Comment by Heporis** [comment]
由于系统变量里没有wget，导致这个问题，
![image](https://user-images.githubusercontent.com/51895154/151648690-78eaff70-d52a-4699-bb8c-fa1730c37d32.png)

**Comment by Heporis** [comment]
这是怎么回事儿
![image](https://user-images.githubusercontent.com/51895154/151649010-975eb423-39a3-420b-aa28-8dbbedcf801b.png)

**Comment by Freddd13** [comment]
输入文件夹下面不要放非音乐文件和其他文件夹，你看你把输出的文件夹放输入里面了，到时候就把它也读进去了

**Comment by Freddd13** [comment]
wget是运行就报错吗？模型打包在里面了，应该不会用到wget

**Comment by Freddd13** [comment]
其他的问题：
1。阿里云盘上传了但是不知道为什么没法分享，有空我再看下
2。cuda用的是qpt打包工具打包的，cpu是比gpu慢太多。这里打包就是为了方便安装 ，你要能自己装环境不怕麻烦可以直接clone gui的代码。（其实这个打包工具很迷，但暂时没啥好方案，懒得折腾..)
3。文件路径最好别用中文

**Comment by Heporis** [comment]
> wget是运行就报错吗？模型打包在里面了，应该不会用到wget

运行就报错，你看那个图里面filenotfound，就是需要wget来下载那两个文件的，打包了wget但是没写入环境变量，系统找不到。
输出文件夹这样设置，批量的时候会报错，单个的时候没问题😂
阿里是限制了压缩包的分享，需要修改文件头信息把压缩包伪装成jpg等文件😥看来天翼更好

**Comment by Freddd13** [comment]
wget是相对路径引用的，理论上是不小心删了模型才会去下模型。我电脑上没走下载这个步骤..
单个文件直接指定了音频文件的路径，但是批量是遍历了文件夹下的东西，这逻辑是原来包里面的我没改（bushi

**Comment by Heporis** [comment]
> wget是相对路径引用的，理论上是不小心删了模型才会去下模型。我电脑上没走下载这个步骤.. 单个文件直接指定了音频文件的路径，但是批量是遍历了文件夹下的东西，这逻辑是原来包里面的我没改（bushi

那两个.mat文件确实打包进去了，一直在resources文件夹里面我也没有删除，但是不知道它为什么非要下载，不直接拷贝过去😅
安装完了，opt和resources是不是就可以删了啊？

**Comment by Freddd13** [comment]
我觉得只能尝试删下opt/package 里面是python包 别的应该不行
另外下载那个破案了，原项目里面还有个download_checkpoint。。 整吐了
