### ISSUE TITLE
Mat file appears to be empty

### ISSUE THREAD

**Issue by qq759979949** [Freddd13/music-separation-gui#2]
你好，我的软件页面可以打开，点击run出现以下错误，请问该如何解决
Link to console: success.
13:05:19	C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
13:05:19	Using cpu for separating ..
13:05:20	-----以下为异常信息-----
13:05:20	Traceback (most recent call last):
13:05:20	  File "C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\qgui\base_tools.py", line 169, in new_func
    func(obj)
13:05:20	  File "C:\Users\Administrator\Desktop\Release\resources\MainUI.py", line 232, in run_single
    progress = self
13:05:20	  File "C:\Users\Administrator\Desktop\Release\resources\SepProcessor.py", line 143, in separate_file
    separator = build_separator(config_yaml, checkpoint_path, device)
13:05:20	  File "C:\Users\Administrator\Desktop\Release\resources\SepProcessor.py", line 65, in build_separator
    target_sources_num=target_sources_num,
13:05:20	  File "C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\bytesep\models\resunet_subbandtime.py", line 237, in __init__
    project_root='bytesep/models/subband_tools/filters',
13:05:20	  File "C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\bytesep\models\subband_tools\pqmf.py", line 64, in __init__
    data = load_mat2numpy(op.join(filters_dir, "f_" + self.name))
13:05:20	  File "C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\bytesep\models\subband_tools\pqmf.py", line 30, in load_mat2numpy
    return loadmat(fname)
13:05:20	  File "C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\scipy\io\matlab\mio.py", line 225, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
13:05:20	  File "C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\scipy\io\matlab\mio.py", line 74, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
13:05:20	  File "C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\scipy\io\matlab\miobase.py", line 214, in get_matfile_version
    raise MatReadError("Mat file appears to be empty")
13:05:20	scipy.io.matlab.miobase.MatReadError: Mat file appears to be empty
13:05:20	None
13:05:20	-----以上为异常信息-----
13:06:18	Using cpu for separating ..
13:06:18	-----以下为异常信息-----
13:06:18	Traceback (most recent call last):
13:06:18	  File "C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\qgui\base_tools.py", line 169, in new_func
    func(obj)
13:06:18	  File "C:\Users\Administrator\Desktop\Release\resources\MainUI.py", line 232, in run_single
    progress = self
13:06:18	  File "C:\Users\Administrator\Desktop\Release\resources\SepProcessor.py", line 143, in separate_file
    separator = build_separator(config_yaml, checkpoint_path, device)
13:06:18	  File "C:\Users\Administrator\Desktop\Release\resources\SepProcessor.py", line 65, in build_separator
    target_sources_num=target_sources_num,
13:06:18	  File "C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\bytesep\models\resunet_subbandtime.py", line 237, in __init__
    project_root='bytesep/models/subband_tools/filters',
13:06:18	  File "C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\bytesep\models\subband_tools\pqmf.py", line 64, in __init__
    data = load_mat2numpy(op.join(filters_dir, "f_" + self.name))
13:06:18	  File "C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\bytesep\models\subband_tools\pqmf.py", line 30, in load_mat2numpy
    return loadmat(fname)
13:06:18	  File "C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\scipy\io\matlab\mio.py", line 225, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
13:06:18	  File "C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\scipy\io\matlab\mio.py", line 74, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
13:06:18	  File "C:\Users\Administrator\Desktop\Release\Python\Lib\site-packages\scipy\io\matlab\miobase.py", line 214, in get_matfile_version
    raise MatReadError("Mat file appears to be empty")
13:06:18	scipy.io.matlab.miobase.MatReadError: Mat file appears to be empty
13:06:18	None
13:06:18	-----以上为异常信息-----

**Comment by Freddd13** [comment]
你好，如果你有Nvidia 显卡，请参考这个https://blog.csdn.net/weixin_44493841/article/details/103827326  安装显卡驱动后重启，然后再尝试运行，如再报错可再反馈

**Comment by Freddd13** [comment]
我更新了版本。如果你使用最新版本且驱动装好后还有问题，可以再打开这个Issue
