### ISSUE TITLE
Unexpected key(s) in state_dict: "istft.ola_window".

### ISSUE THREAD

**Issue by playdasegunda** [Freddd13/music-separation-gui#3]
**Describe the bug**
I'm getting the following problem when trying to process, before it worked, now I'm getting this error what could it be?

LOG BUG:

```
Link to console: success.
08:09:14	GPU:  NVIDIA GeForce RTX 2060
08:09:14	Using cuda for separating ..
08:09:16	-----以下为异常信息-----
08:09:16	Traceback (most recent call last):
08:09:16	  File "C:\Users\lucas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\qgui\base_tools.py", line 169, in new_func
    func(obj)
08:09:16	  File "C:\Program Files (x86)\Music_Separation_GUI_v002_amd64\Release\resources\MainUI.py", line 232, in run_single
    progress = self
08:09:16	  File "C:\Program Files (x86)\Music_Separation_GUI_v002_amd64\Release\resources\SepProcessor.py", line 142, in separate_file
    separator = build_separator(config_yaml, checkpoint_path, device)
08:09:16	  File "C:\Program Files (x86)\Music_Separation_GUI_v002_amd64\Release\resources\SepProcessor.py", line 70, in build_separator
    model.load_state_dict(checkpoint["model"])
08:09:16	  File "C:\Users\lucas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\torch\nn\modules\module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
08:09:16	RuntimeError: Error(s) in loading state_dict for ResUNet143_Subbandtime:
	Missing key(s) in state_dict: "istft.reverse.weight", "istft.overlap_add.weight". 
	Unexpected key(s) in state_dict: "istft.ola_window". 
08:09:16	None
08:09:16	-----以上为异常信息-----


```

**Expected behavior**
Hope it works like it used to

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/97372669/162569455-b7559dd7-16c6-4ad2-b425-49451a1aeed2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 
**Device information**
 - graphic card: * RTX 2060
- cpu: Intel core I7 10705H

**Comment by Freddd13** [comment]
Hi, lucas. Are you using GUI only or the full package？ I think it is caused by an improper torch version. If you install torch by yourself, you should install 1.7.1 version.

**Comment by Freddd13** [comment]
Besides, I found that you are not using the latest version. Please refer to the release to get 003 version. It should work fine.

**Comment by User0404** [comment]
16:36:25	Traceback (most recent call last):
16:36:25	  File "D:\__easyHelper__\Python\Lib\site-packages\qgui\base_tools.py", line 169, in new_func
    func(obj)
16:36:25	  File "D:\__easyHelper__\resources\MainUI.py", line 232, in run_single
    progress = self
16:36:25	  File "D:\__easyHelper__\resources\SepProcessor.py", line 149, in separate_file
    audio = load_audio(audio_path=audio_path, mono=False, sample_rate=sample_rate)  # audio: (input_channels, audio_samples)
16:36:25	  File "D:\__easyHelper__\Python\Lib\site-packages\bytesep\utils.py", line 62, in load_audio
    audio_path, sr=sample_rate, mono=mono, offset=offset, duration=duration
16:36:25	  File "D:\__easyHelper__\Python\Lib\site-packages\librosa\core\audio.py", line 163, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
16:36:25	  File "D:\__easyHelper__\Python\Lib\site-packages\librosa\core\audio.py", line 187, in __audioread_load
    with audioread.audio_open(path) as input_file:
16:36:25	  File "D:\__easyHelper__\Python\Lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
16:36:25	audioread.exceptions.NoBackendError
16:36:25	None





请问这是什么问题呢？
cpu  R5 
显卡 rtx 1650

**Comment by Freddd13** [comment]
你好 @User0404 。你这个是因为没有安装ffmpeg, 十分抱歉，因为我的失误，以为上次修改后已经不需要ffmpeg依赖，实际上有个包还是需要的。你可以尝试将解压后的 `resources/tools`目录加入[环境变量](https://jingyan.baidu.com/article/00a07f3876cd0582d128dc55.html)，因为暂时没装虚拟机没法测试不保证这个能成功，不过这可能是最简单的方法。
如果还是不行，请参考[这里](https://blog.csdn.net/qq_43803367/article/details/110308401)安装 ffmpeg并将其加入环境变量

Sent with a Spark
在 2022年4月10日 +0800 16:40，User0404 ***@***.***>，写道：

**Comment by playdasegunda** [comment]
Good afternoon, sorry for the late reply,

Unfortunately I'm still facing the same problem reported,

I downloaded the package with the latest version of this GUI but I still get the error "istft.ola_window"

I have no idea what it could be,

I can only say that probably the problem is because I have installed some pip dependency, but I don't know what it is, do you have an idea what it might be?

**Comment by Freddd13** [comment]
@lucasbr15 How do you launch the program? Please just open *run.exe* to launch instead of using python MainUI.py.
Remeber if you run it for the first time, you need to run `install.cmd` first.

> To install, run install.cmd.

> Wait the terminal to download and install packages. If you encounter a win32 dll import error, try to run the fix_win32_error.bat.

> This may take some time, please be patient. If it is stuck for too long, please try to press "Enter" on your keyboard!!! (This problem may only occurs during the first opening.)

> After the first installation, you can quickly start the program by running run.exe in the future. In fact, the install.cmd will provoke the run.exe. The former is to deal with torch packages, so there's no need to run it after the installation.

**Comment by playdasegunda** [comment]
Hello;

When running run.exe I get the following error
![Screenshot_1](https://user-images.githubusercontent.com/97372669/163565968-2e426dad-f84d-484d-b399-7f21e453c3d4.png)

**Comment by Freddd13** [comment]
The directory you use should not contain a space.

**Comment by playdasegunda** [comment]
Good afternoon, now it is working 100% I moved the Programs Files folder to Downloads, and installed torch torch 1.11.0+cu113 and it seems to work, probably the error I was getting was because I was using torch 1.9.0, I am running it from the exe file as suggested and it is also working normally now, thanks a lot for the help!

**Comment by Freddd13** [comment]
In fact, if you have a torch environment, you don't need the full package lol but just the code as I mentioned in README.md. This package is large because it contains a independent python environment and cuda. 
Anyway, glad to help you run successfully. Good luck.
