### ISSUE TITLE
Request to update checkpoint models

### ISSUE THREAD

**Issue by playdasegunda** [Freddd13/music-separation-gui#5]
Hello how are you? I ended up noticing that your ByteDance GUI is using the checkpoints models:

resunet143_subbtandtime_vocals_**8.7dB**_500k_steps_v2.pth
resunet143_subbtandtime_accompaniment_**16.4dB**_500k_steps_v2.pth

However, the models that have the best performance in SDR is resunet143_ismir2021, with (**8.9dB** on Vocals) and (**16.8dB** on Accompaniment), would it be possible for you to make the substitution to include these better models?

I've been making some changes to the .yaml files trying to adapt them to your gui but the end result is the vocal or instrumental containing very loud noises, so no one better than you to make the other models compatible with your gui;

**LINK CHECKPOINTS MODELS**: https://zenodo.org/record/5513378
**REPO**: https://github.com/bytedance/music_source_separation/tree/kqq

I look forward to hearing from you, thank you.

**Comment by Freddd13** [comment]
For personal entertainment, I think there's no large difference between these two models. 
The models you mentioned above need `inplace-abn` which is painful to install on windows. For this reason, currently I don't want to pack it. However, if you managed to install it, here provides the two yamls for you, but note that currently there's not a saving config function, you have to select your yaml everytime you start the program. 

For accomp: https://github.com/Freddd13/file/blob/main/accompaniment-vocals%2Cresunet_ismir2021.yaml
For vocal: https://github.com/Freddd13/file/blob/main/vocals-accompaniment%2Cresunet_ismir2021.yaml

**Comment by playdasegunda** [comment]
didn't work, i got the same error as when i tried to import yaml ismir, without trying to make any modification, but thanks anyway.
